candles_config: []
candles_connector: okx
candles_trading_pair: BTC-USDT
close_position_on_signal_change: true
connector_name: okx
controller_name: xgridt
controller_type: generic
cooldown_time: 60
distance_between_peaks: 20
donchian_channel_length: 100
ema_long: 66
ema_medium: 40
ema_short: 3
executor_activation_bounds: 0.001
extra_balance_base_usd: 10
general_activation_bounds: 0.001
global_stop_loss: 0.1
grid_update_interval: null
id: xgridt_spot_BTC_USDT_20250404163550
interval: 1m
leverage: 1
manual_kill_switch: null
max_executors_per_side: 3
max_open_orders: 5
max_ranges_by_signal: 1
min_order_amount: 1
min_spread_between_orders: 0.001
natr_length: 130
natr_multiplier: 1.2000000000000002
order_frequency: 0
position_mode: ONE_WAY
prominence_pct_peaks: 0.034999999999999996
take_profit_mode: original
take_profit_step_multiplier: 1
time_limit: 7200
total_amount_quote: 100.0
tp_default: 0.036000000000000004
trading_pair: BTC-USDT
