candles_config: []
candles_connector: okx
candles_trading_pair: XRP-USDT
close_position_on_signal_change: true
connector_name: okx
controller_name: xgridt
controller_type: generic
cooldown_time: 60
distance_between_peaks: 60
donchian_channel_length: 90
ema_long: 29
ema_medium: 17
ema_short: 6
executor_activation_bounds: 0.001
extra_balance_base_usd: 10
general_activation_bounds: 0.001
global_stop_loss: 0.1
grid_update_interval: null
id: xgridt_spot_XRP_USDT_20250404163553
interval: 1m
leverage: 1
manual_kill_switch: null
max_executors_per_side: 3
max_open_orders: 5
max_ranges_by_signal: 1
min_order_amount: 1
min_spread_between_orders: 0.001
natr_length: 100
natr_multiplier: 1.9000000000000001
order_frequency: 0
position_mode: ONE_WAY
prominence_pct_peaks: 0.04
take_profit_mode: original
take_profit_step_multiplier: 1
time_limit: 7200
total_amount_quote: 700.0
tp_default: 0.032
trading_pair: XRP-USDT
