# PMM Simple Backtesting Task Configuration
---
tasks:
  PMM_Simple_Backtesting:
    task_class: "tasks.backtesting.pmm_simple_backtesting_task.PMMSimpleBacktestingTask"
    config:
      # Backtesting parameters
      connector_name: "okx"
      backtesting_interval: "1s"  
      interval: "1m"  
      # Time range configuration - use either absolute or relative time range
      # Absolute time range (takes precedence if both are provided)
      start_time: "2025-04-08 18:40:00"  
      end_time: "2025-04-08 19:00:00"
      
      n_trials: 1000
      total_amount_quote: 100
      study_name_suffix: "cooldown_test"
      # debug_trial: 742
      # Trading pairs to backtest
      selected_pairs:
        - "ADA-USDT"
        