tasks:
  pmm_vml_model_training:
    task_class: "tasks.training.pmm_vml_model_training.PMMVMLModelTrainingTask"
    config:
      # Paths
      feature_label_data_path: data/features_labels/  # Path to input feature/label CSVs
      model_output_path: data/models/pmm_vml/  # Path for output models/scalers
      
      # Trading pairs to train models for
      trading_pairs:
        - ADA-USDT
        - CRV-USDT
        - BTC-USDT
        - AVAX-USDT
        - AAVE-USDT
        - APT-USDT
        - EIGEN-USDT
        - HBAR-USDT
        - ETH-USDT
        - KAITO-USDT
        - XRP-USDT
      
      # Train-test split parameters
      test_size: 0.2
      random_state: 42
      
      # Model parameters for RandomForestRegressor
      model_params:
        n_estimators: 100
        max_depth: 10
        min_samples_split: 2
        min_samples_leaf: 1
        n_jobs: -1  # Use all available cores 