tasks:
  PMM_Simple_Label_Generation:
    task_class: "tasks.backtesting.pmm_label_generation_task.PMMLabelGenerationTask"
    config:
      # Backtesting parameters
      connector_name: "okx"
      backtesting_interval: "1s"  
      # candle_interval: "1m"  
      start_time: "2025-04-08 12:00:00"  
      end_time: "2025-04-09 13:00:00"    
      backtest_offset: 1
      backtest_window_step: 60
      backtest_window_size: 300
      
      n_trials: 100
      # n_trials: 2
      total_amount_quote: 100
      # study_name_suffix: "cooldown_test"
      # debug_trial: 72
      # force_new_study: True
      # debug_study: "pmm_simple_label_generation_ADA-USDT_1s_101__1744135500.0"
      
      # Trading pairs to backtest
      selected_pairs:
        - "ADA-USDT"
        