# XGridT Backtesting Task Configuration (Original Version)
---
tasks:
  XGridT_Backtesting:
    task_class: "tasks.backtesting.xgridt_backtesting_task_2.XGridTBacktestingTask"
    frequency_hours: 24  # Run once per day
    name: "XGridT Backtesting Original"
    config:
      # Path to project root
      root_path: "../.."

      # Backtesting parameters
      connector_name: "okx"
      interval: "1m"
      lookback_days: 7  # 7-day backtest period
      end_time_buffer_hours: 6  # Hours from now to exclude in backtesting
      n_trials: 1000
      max_parallel_trials: 16
      total_amount: 100
      
      # Trading pairs to backtest
      selected_pairs:
        - "ADA-USDT"
        - "AAVE-USDT"
        - "AVAX-USDT"
        - "APT-USDT"
        - "EIGEN-USDT"
        - "HBAR-USDT"
        - "BTC-USDT"
        - "ETH-USDT"
        - "CRV-USDT"
        - "KAITO-USDT"
        - "XRP-USDT" 